pub const BOOTLOADER_PREPARE_SIMPLE_BOOTLOADER_OUTPUT_SEGMENT: &str =
    "BOOTLOADER_PREPARE_SIMPLE_BOOTLOADER_OUTPUT_SEGMENT";

pub const BOOTLOADER_PREPARE_SIMPLE_BOOTLOADER_INPUT: &str =
    "BOOTLOADER_PREPARE_SIMPLE_BOOTLOADER_INPUT";

pub const BOOTLOADER_READ_SIMPLE_BOOTLOADER_INPUT: &str = "BOOTLOADER_READ_SIMPLE_BOOTLOADER_INPUT";

pub const BOOTLOADER_READ_UNPACKER_BOOTLOADER_INPUT: &str =
    "BOOTLOADER_READ_UNPACKER_BOOTLOADER_INPUT";

pub const BOOTLOADER_RESTORE_BOOTLOADER_OUTPUT: &str = "BOOTLOADER_RESTORE_BOOTLOADER_OUTPUT";

pub const BOOTLOADER_LOAD_BOOTLOADER_CONFIG: &str = "BOOTLOADER_LOAD_BOOTLOADER_CONFIG";

pub const BOOTLOADER_ENTER_PACKED_OUTPUT_SCOPE: &str = "BOOTLOADER_ENTER_PACKED_OUTPUT_SCOPE";

pub const BOOTLOADER_IMPORT_PACKED_OUTPUT_SCHEMAS: &str = "BOOTLOADER_IMPORT_PACKED_OUTPUT_SCHEMAS";

// Appears as nondet %{ isinstance(packed_output, PlainPackedOutput) %} in the code.
pub const BOOTLOADER_IS_PLAIN_PACKED_OUTPUT: &str =
    "memory[ap] = to_felt_or_relocatable(isinstance(packed_output, PlainPackedOutput))";

pub const BOOTLOADER_PROGRAM_HASH: &str =
    "memory[ap] = to_felt_or_relocatable(task.program_hash_function)";

pub const BOOTLOADER_VALIDATE_HASH: &str = "# Validate hash.
from starkware.cairo.bootloaders.hash_program import compute_program_hash_chain

assert memory[ids.output_ptr + 1] == compute_program_hash_chain(
    program=task.get_program(),
    use_poseidon=bool(ids.use_poseidon)), 'Computed hash does not match input.'";

pub const BOOTLOADER_SAVE_OUTPUT_POINTER: &str = "BOOTLOADER_SAVE_OUTPUT_POINTER";

pub const BOOTLOADER_SAVE_PACKED_OUTPUTS: &str = "BOOTLOADER_SAVE_PACKED_OUTPUTS";

pub const BOOTLOADER_COMPUTE_FACT_TOPOLOGIES: &str = "BOOTLOADER_COMPUTE_FACT_TOPOLOGIES";

pub const BOOTLOADER_SIMPLE_BOOTLOADER_COMPUTE_FACT_TOPOLOGIES: &str =
    "BOOTLOADER_SIMPLE_BOOTLOADER_COMPUTE_FACT_TOPOLOGIES";

pub const BOOTLOADER_GUESS_PRE_IMAGE_OF_SUBTASKS_OUTPUT_HASH: &str =
    "BOOTLOADER_GUESS_PRE_IMAGE_OF_SUBTASKS_OUTPUT_HASH";

pub const BOOTLOADER_SET_PACKED_OUTPUT_TO_SUBTASKS: &str =
    "BOOTLOADER_SET_PACKED_OUTPUT_TO_SUBTASKS";

pub const BOOTLOADER_ASSERT_IS_COMPOSITE_PACKED_OUTPUT: &str =
    "BOOTLOADER_ASSERT_IS_COMPOSITE_PACKED_OUTPUT";

pub const SETUP_RUN_SIMPLE_BOOTLOADER_BEFORE_TASK_EXECUTION: &str =
    "SETUP_RUN_SIMPLE_BOOTLOADER_BEFORE_TASK_EXECUTION";

// Appears as nondet %{ ids.num // 2 %} in the code.
pub const SIMPLE_BOOTLOADER_DIVIDE_NUM_BY_2: &str =
    "memory[ap] = to_felt_or_relocatable(ids.num // 2)";

pub const SIMPLE_BOOTLOADER_SET_CURRENT_TASK: &str = "SIMPLE_BOOTLOADER_SET_CURRENT_TASK";

pub const DETERMINE_USE_PREV_HASH: &str = "DETERMINE_USE_PREV_HASH";

// Appears as nondet %{ 0 %} in the code.
pub const SIMPLE_BOOTLOADER_ZERO: &str = "memory[ap] = to_felt_or_relocatable(0)";

pub const LOAD_PROGRAM_SEGMENT: &str = "LOAD_PROGRAM_SEGMENT";

pub const EXECUTE_TASK_VALIDATE_HASH: &str = "# Validate hash.
from starkware.cairo.bootloaders.hash_program import compute_program_hash_chain

assert memory[ids.output_ptr + 1] == compute_program_hash_chain(task.get_program()), \\
  'Computed hash does not match input.'";

pub const EXECUTE_TASK_ASSERT_PROGRAM_ADDRESS: &str = "EXECUTE_TASK_ASSERT_PROGRAM_ADDRESS";

pub const EXECUTE_TASK_CALL_TASK: &str = "EXECUTE_TASK_CALL_TASK";

pub const EXECUTE_TASK_EXIT_SCOPE: &str = "EXECUTE_TASK_EXIT_SCOPE";

pub const EXECUTE_TASK_WRITE_RETURN_BUILTINS: &str = "EXECUTE_TASK_WRITE_RETURN_BUILTINS";

pub const EXECUTE_TASK_APPEND_FACT_TOPOLOGIES: &str = "EXECUTE_TASK_APPEND_FACT_TOPOLOGIES";

pub const SELECT_BUILTINS_ENTER_SCOPE: &str = "SELECT_BUILTINS_ENTER_SCOPE";

pub const INNER_SELECT_BUILTINS_SELECT_BUILTIN: &str = "INNER_SELECT_BUILTINS_SELECT_BUILTIN";

pub const VERIFIER_LOAD_AND_PARSE_PROOF: &str = "VERIFIER_LOAD_AND_PARSE_PROOF";

pub const VERIFIER_GET_INDEX_LAST_BIT: &str = "VERIFIER_GET_INDEX_LAST_BIT";

pub const VERIFIER_DIVIDE_QUERIES_IND_BY_COSET_SIZE_TO_FP_OFFSET: &str =
    "memory[fp + 1] = to_felt_or_relocatable(ids.queries.index // ids.params.coset_size)";

pub const APPLICATIVE_LOAD_INPUTS: &str = "APPLICATIVE_LOAD_INPUTS";

pub const APPLICATIVE_SET_UP_UNPACKER_INPUTS: &str = "APPLICATIVE_SET_UP_UNPACKER_INPUTS";

pub const APPLICATIVE_RESTORE_OUTPUT_BUILTIN_STATE: &str =
    "APPLICATIVE_RESTORE_OUTPUT_BUILTIN_STATE";

pub const APPLICATIVE_FINALIZE_FACT_TOPOLOGIES_AND_PAGES: &str =
    "APPLICATIVE_FINALIZE_FACT_TOPOLOGIES_AND_PAGES";

pub const SIMPLE_OUTPUT_LOAD_PROGRAM_INPUT: &str = "SIMPLE_OUTPUT_LOAD_PROGRAM_INPUT";

pub const SIMPLE_OUTPUT_WRITE_OUTPUT: &str = "SIMPLE_OUTPUT_WRITE_OUTPUT";

pub const SIMPLE_OUTPUT_LEN_OUTPUT_TO_AP: &str = "memory[ap] = to_felt_or_relocatable(len(output))";

pub const MOCK_CAIRO_VERIFIER_LOAD_INPUT: &str = "MOCK_CAIRO_VERIFIER_LOAD_INPUT";

pub const MOCK_CAIRO_VERIFIER_OUTPUT_LEN_TO_FP: &str =
    "memory[fp + 1] = to_felt_or_relocatable(len(program_output))";

pub const MOCK_CAIRO_VERIFIER_HASH_TO_FP: &str =
    "memory[fp + 2] = to_felt_or_relocatable(program_hash)";

pub const MOCK_CAIRO_VERIFIER_GET_N_STEPS: &str = "MOCK_CAIRO_VERIFIER_GET_N_STEPS";

pub const MOCK_CAIRO_VERIFIER_N_STEPS_TO_AP: &str = "memory[ap] = to_felt_or_relocatable(n_steps)";

pub const SIMPLE_BOOTLOADER_SIMULATE_EC_OP: &str = "SIMPLE_BOOTLOADER_SIMULATE_EC_OP";

pub const SIMULATE_EC_OP_FILL_MEM_WITH_BITS_OF_M: &str = "SIMULATE_EC_OP_FILL_MEM_WITH_BITS_OF_M";

pub const SIMULATE_EC_OP_ASSERT_FALSE: &str = "assert False, \"ec_op failed.\"";

pub const SIMPLE_BOOTLOADER_SIMULATE_KECCAK: &str = "SIMPLE_BOOTLOADER_SIMULATE_KECCAK";

pub const SIMULATE_KECCAK_FILL_MEM_WITH_STATE: &str = "SIMULATE_KECCAK_FILL_MEM_WITH_STATE";

pub const SIMULATE_KECCAK_CALC_HIGH3_LOW3: &str = "SIMULATE_KECCAK_CALC_HIGH3_LOW3";

pub const SIMULATE_KECCAK_CALC_HIGH6_LOW6: &str = "SIMULATE_KECCAK_CALC_HIGH6_LOW6";

pub const SIMULATE_KECCAK_CALC_HIGH9_LOW9: &str = "SIMULATE_KECCAK_CALC_HIGH9_LOW9";

pub const SIMULATE_KECCAK_CALC_HIGH12_LOW12: &str = "SIMULATE_KECCAK_CALC_HIGH12_LOW12";

pub const SIMULATE_KECCAK_CALC_HIGH15_LOW15: &str = "SIMULATE_KECCAK_CALC_HIGH15_LOW15";

pub const SIMULATE_KECCAK_CALC_HIGH18_LOW18: &str = "SIMULATE_KECCAK_CALC_HIGH18_LOW18";

pub const SIMULATE_KECCAK_CALC_HIGH21_LOW21: &str = "SIMULATE_KECCAK_CALC_HIGH21_LOW21";

pub const SIMPLE_BOOTLOADER_SIMULATE_ECDSA: &str = "SIMPLE_BOOTLOADER_SIMULATE_ECDSA";
pub const SIMULATE_ECDSA_GET_R_AND_S: &str = "SIMULATE_ECDSA_GET_R_AND_S";

pub const SIMULATE_ECDSA_COMPUTE_W_WR_WZ: &str = "SIMULATE_ECDSA_COMPUTE_W_WR_WZ";

pub const SIMULATE_ECDSA_FILL_MEM_WITH_FELT_96_BIT_LIMBS: &str =
    "SIMULATE_ECDSA_FILL_MEM_WITH_FELT_96_BIT_LIMBS";

pub const CONCAT_AGGREGATOR_PARSE_TASKS_OUTPUTS: &str = "CONCAT_AGGREGATOR_PARSE_TASKS_OUTPUTS";

pub const CONCAT_AGGREGATOR_GET_TASK_OUTPUT_WITH_SIZE: &str =
    "CONCAT_AGGREGATOR_GET_TASK_OUTPUT_WITH_SIZE";

pub const CONCAT_AGGREGATOR_GET_TASK_OUTPUT_WITHOUT_SIZE: &str =
    "CONCAT_AGGREGATOR_GET_TASK_OUTPUT_WITHOUT_SIZE";

pub const CONCAT_AGGREGATOR_SET_PAGES_AND_FACT_TOPOLOGY: &str =
    "CONCAT_AGGREGATOR_SET_PAGES_AND_FACT_TOPOLOGY";

pub const BUILTIN_USAGE_SET_MAX_SIZE_PAGES_AND_FACT_TOPOLOGY: &str =
    "BUILTIN_USAGE_SET_MAX_SIZE_PAGES_AND_FACT_TOPOLOGY";

pub const BUILTIN_USAGE_ADD_OTHER_SEGMENT_FINALIZE: &str =
    "BUILTIN_USAGE_ADD_OTHER_SEGMENT_FINALIZE";

pub const BUILTIN_USAGE_ADD_OTHER_SEGMENT: &str = "BUILTIN_USAGE_ADD_OTHER_SEGMENT";

pub const BUILTIN_USAGE_ADD_SIGNATURE: &str = "BUILTIN_USAGE_ADD_SIGNATURE";

pub const BUILTIN_USAGE_5_TO_AP: &str = "BUILTIN_USAGE_5_TO_AP";

pub const BUILTIN_USAGE_SET_PAGES_AND_FACT_TOPOLOGY: &str =
    "BUILTIN_USAGE_SET_PAGES_AND_FACT_TOPOLOGY";

pub const FLEXIBLE_BUILTIN_USAGE_FROM_INPUT: &str = "FLEXIBLE_BUILTIN_USAGE_FROM_INPUT";

pub const BUILTIN_USAGE_ADD_SIGNATURE_FROM_SIGNATURE_BUILTIN_STRUCT: &str =
    "BUILTIN_USAGE_ADD_SIGNATURE_FROM_SIGNATURE_BUILTIN_STRUCT";

pub const FIBONACCI_LOAD_SECOND_ELEMENT: &str = "FIBONACCI_LOAD_SECOND_ELEMENT";

pub const FIBONACCI_LOAD_CLAIM_IDX: &str = "FIBONACCI_LOAD_CLAIM_IDX";

pub const PEDERSEN_MERKLE_LOAD_INPUT: &str = "PEDERSEN_MERKLE_LOAD_INPUT";

pub const PEDERSEN_MERKLE_VERIFY_AUTH_PATH_LEN: &str = "PEDERSEN_MERKLE_VERIFY_AUTH_PATH_LEN";

pub const PEDERSEN_MERKLE_IDX_PARITY_TO_AP: &str = "PEDERSEN_MERKLE_IDX_PARITY_TO_AP";

pub const PEDERSEN_MERKLE_UPDATE_LEFT: &str = "PEDERSEN_MERKLE_UPDATE_LEFT";

pub const PEDERSEN_MERKLE_UPDATE_RIGHT: &str = "PEDERSEN_MERKLE_UPDATE_RIGHT";
