[package]
name = "leaf_prover"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Run Cairo programs, prove their runs, verify that proof with a circuit-cairo verifier and output a proof of the run of that circuit"


[dependencies]
cairo-program-runner-lib.workspace = true
cairo-vm.workspace = true
clap.workspace = true
sonic-rs.workspace = true
tracing.workspace = true
indexmap = { version = "2.10.0", default-features = false, features = ["std"] }

# Pin a specific stwo-circuits revision to keep the verifier circuit stable
circuit-cairo-verifier = { git = "https://github.com/starkware-libs/stwo-circuits", rev = "a40dcba" }
circuits-stark-verifier = { git = "https://github.com/starkware-libs/stwo-circuits", rev = "a40dcba" }
circuit-prover = { git = "https://github.com/starkware-libs/stwo-circuits", rev = "a40dcba" }
circuit-common = { git = "https://github.com/starkware-libs/stwo-circuits", rev = "a40dcba" }
circuit-serialize = { git = "https://github.com/starkware-libs/stwo-circuits", rev = "a40dcba" }

# Use the same stwo-cairo commit as used by the above stwo-circuits
cairo-air = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "3a3f592" }
stwo-cairo-adapter = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "3a3f592" }
stwo-cairo-common = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "3a3f592" }
stwo-cairo-prover = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "3a3f592" }
stwo-cairo-utils = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "3a3f592" }