[package]
name = "privacy-prove"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Run Cairo programs and generate STWO proofs that can be verified with a cairo-circuit verifier"

[features]
slow-tests = []

[dependencies]
anyhow.workspace = true
clap.workspace = true
itertools.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
sonic-rs.workspace = true
starknet-ff.workspace = true
starknet-types-core.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tracing.workspace = true
zstd.workspace = true

# local crates
cairo-program-runner-lib.workspace = true
privacy-circuit-verify.workspace = true

# cairo-vm
cairo-vm = { workspace = true, features = [
    "extensive_hints",
    "mod_builtin",
    "clap",
] }

# stwo cairo
cairo-air = { path = "../../../stwo-cairo/stwo_cairo_prover/crates/cairo-air" }
stwo-cairo-adapter = { path = "../../../stwo-cairo/stwo_cairo_prover/crates/adapter" }
stwo-cairo-prover = { path = "../../../stwo-cairo/stwo_cairo_prover/crates/prover" }
stwo-cairo-serialize = { path = "../../../stwo-cairo/stwo_cairo_prover/crates/cairo-serialize" }
stwo-cairo-common = { path = "../../../stwo-cairo/stwo_cairo_prover/crates/common" }

# stwo circuits
circuit-cairo-air = { path = "../../../stwo-circuits/crates/cairo_air" }
circuits-stark-verifier = { path = "../../../stwo-circuits/crates/stark_verifier" }
circuits = { path = "../../../stwo-circuits/crates/circuits" }
circuit-serialize = { path = "../../../stwo-circuits/crates/circuit_serialize" }
circuit-prover = { path = "../../../stwo-circuits/crates/circuit_prover" }
circuit-common = { path = "../../../stwo-circuits/crates/circuit_common" }
circuit-air = { path = "../../../stwo-circuits/crates/circuit_air" }

# stwo
stwo = { path = "../../../../stwo/crates/stwo", features = ["parallel", "prover"] }

[dev-dependencies]
ctor.workspace = true
mockall.workspace = true
rstest.workspace = true
tracing-subscriber.workspace = true
