[package]
name = "privacy-prove"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Run Cairo programs and generate STWO proofs that can be verified with a cairo-circuit verifier"

[features]
slow-tests = []

[dependencies]
anyhow.workspace = true
clap.workspace = true
itertools.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
sonic-rs.workspace = true
starknet-ff.workspace = true
starknet-types-core.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tracing.workspace = true

# local crates
cairo-program-runner-lib.workspace = true
privacy-circuit-verify.workspace = true

# cairo-vm
cairo-vm = { workspace = true, features = [
    "extensive_hints",
    "mod_builtin",
    "clap",
] }

# stwo cairo
cairo-air.workspace = true
stwo-cairo-adapter.workspace = true
stwo-cairo-prover.workspace = true
stwo-cairo-serialize.workspace = true
stwo-cairo-common.workspace = true

# stwo circuits
circuit-cairo-air.workspace = true
circuits-stark-verifier.workspace = true
circuits.workspace = true
circuit-serialize.workspace = true
circuit-prover.workspace = true
circuit-common.workspace = true
circuit-air.workspace = true

# stwo
stwo = { workspace = true, features = ["parallel", "prover"] }


[dev-dependencies]
ctor.workspace = true
mockall.workspace = true
rstest.workspace = true
tracing-subscriber.workspace = true
