[package]
name = "privacy-prove"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Run Cairo programs and generate STWO proofs that can be verified with a cairo-circuit verifier"

[features]
slow-tests = []

[dependencies]
anyhow.workspace = true
itertools.workspace = true
serde_json.workspace = true
starknet-types-core.workspace = true
tempfile.workspace = true
tracing.workspace = true
zstd.workspace = true

# local crates
cairo-program-runner-lib.workspace = true
privacy-circuit-verify.workspace = true

# cairo-vm
cairo-vm = { workspace = true, features = [
    "extensive_hints",
    "mod_builtin",
    "clap",
] }

# stwo cairo
cairo-air = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "d917a99" }
stwo-cairo-adapter = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "d917a99" }
stwo-cairo-prover = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "d917a99" }
stwo-cairo-common = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "d917a99" }

# stwo circuits
circuit-cairo-verifier = { git = "https://github.com/starkware-libs/stwo-circuits", rev = "3425890" }
circuits-stark-verifier = { git = "https://github.com/starkware-libs/stwo-circuits", rev = "3425890" }
circuit-serialize = { git = "https://github.com/starkware-libs/stwo-circuits", rev = "3425890" }
circuit-prover = { git = "https://github.com/starkware-libs/stwo-circuits", rev = "3425890" }
circuit-common = { git = "https://github.com/starkware-libs/stwo-circuits", rev = "3425890" }
circuit-verifier = { git = "https://github.com/starkware-libs/stwo-circuits", rev = "3425890" }

# stwo
stwo = { git = "https://github.com/starkware-libs/stwo", rev = "960b2529", features = ["parallel"] }

[dev-dependencies]
ctor.workspace = true
expect-test.workspace = true
mockall.workspace = true
rstest.workspace = true
tracing-subscriber.workspace = true
