name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rustfmt:
    runs-on: namespace-profile-starkware-libs-proving-utils-medium-ubuntu-24-04-amd64
    steps:
      - uses: actions/checkout@v4
      - run: rustup show
      - run: rustup toolchain install nightly-2025-07-14 --profile minimal
      - run: rustup component add rustfmt --toolchain nightly-2025-07-14
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly-2025-07-14 fmt --all -- --check

  clippy:
    runs-on: namespace-profile-starkware-libs-proving-utils-medium-ubuntu-24-04-amd64
    steps:
      - uses: actions/checkout@v4
      - run: rustup show
      - run: rustup toolchain install nightly-2025-07-14 --profile minimal
      - run: rustup component add clippy --toolchain nightly-2025-07-14
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly-2025-07-14 clippy --workspace --all-targets --all-features -- -D warnings -D future-incompatible -D nonstandard-style -D rust-2018-idioms -D unused

  tests:
    runs-on: namespace-profile-starkware-libs-proving-utils-large-ubuntu-24-04-amd64
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - run: rustup show
      - run: rustup toolchain install nightly-2025-07-14 --profile minimal
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-tarpaulin
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          tool-cache: false
      - name: "Unit tests with coverage"
        run: |
          mkdir -p coverage
          cargo +nightly-2025-07-14 tarpaulin \
            --workspace --all-targets --all-features \
            --out Stdout --out Xml --output-dir coverage \
            --fail-under 0
      - name: "Test examples"
        run: |
          cargo +nightly-2025-07-14 run --example run_program_with_simple_bl
          cargo +nightly-2025-07-14 run --example run_pie_object_with_simple_bl
      - name: "Upload coverage report"
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

  udeps:
    runs-on: namespace-profile-starkware-libs-proving-utils-medium-ubuntu-24-04-amd64
    steps:
      - uses: actions/checkout@v4
      - run: rustup show
      - run: rustup toolchain install nightly-2025-07-14 --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - run: cargo install cargo-udeps --locked
      - run: cargo +nightly-2025-07-14 udeps
