name: codecov

on:
  workflow_run:
    workflows: ["check"]
    types: [completed]

jobs:
  report:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: namespace-profile-starkware-libs-proving-utils-small-ubuntu-24-04-amd64
    steps:
      - name: "Download coverage report"
        uses: dawidd6/action-download-artifact@v3
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: coverage-report
      - name: "Upload to Codecov (optional)"
        uses: codecov/codecov-action@v4
        with:
          files: coverage/cobertura.xml
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
